### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by drlasarus** [StanislavDremin/ab.iblock#1]
Fatal error: Call to a member function addField() on null in /home/bitrix/www/local/modules/ab.iblock/lib/Manager.php on line 113

Предлагаю в файле
/home/bitrix/www/local/modules/ab.iblock/lib/Query.php
заменить строки 39, 40:
`$this->init_entity = $Manager->setElementEntity($this->init_entity)`
на
`$Manager->setElementEntity($this->entity)`

**Comment by StanislavDremin** [comment]
Да, битриксы неожиданно сменили название свойства класса.
заменил init_entity на entity
